version: "3.7"

networks:
    network1:
        external: true
    network2:
        external: true
services: 
  jenkins:
    build:
      context: ./dockerfile
      dockerfile: jenkins
    container_name: jenkins
    user: root
    networks:
      - network1
      - network2
    ports: 
      - 8080:8080
    volumes:
      - /jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true

  robotframework-api:
    build:
      context: ./dockerfile
      dockerfile: robotframework
    container_name: robotframework-api
    networks:
      - network1
    privileged: true
    stdin_open: true
    tty: true

  robotframework-web:
    build:
      context: ./dockerfile
      dockerfile: robotframework1
    container_name: robotframework-web
    networks:
      - network2
    volumes:
      - ./AVUS3.0:/var/work/AVUS3.0
    privileged: true
    stdin_open: true
    tty: true
